Name: Tanaya Pawar Netid : tp2623

Data Science Bootcamp assignment 2

1. ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.


In [13]:
import numpy as np
import pandas as pd

In [14]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [24]:
A = np.array([1, 2, 3, 5, 6])
B = np.array([5, 3, 7, 6, 8])
vertical_AB = np.vstack((A, B))
horizontal_AB = np.hstack((A, B))
print( vertical_AB)
print( horizontal_AB)


[[1 2 3 5 6]
 [5 3 7 6 8]]
[1 2 3 5 6 5 3 7 6 8]


 ⁠2. Find common elements between A and B.

In [25]:
common_elements = np.intersect1d(A, B)
print(common_elements)

[3 5 6]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10.

In [26]:
filtered_numbers = A[(A >= 5) & (A <= 10)]
print(filtered_numbers)

[5 6]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [28]:
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered_iris)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


5. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
selected_columns = ['Manufacturer', 'Model', 'Type']

filtered_cars = df.loc[df.index[::20], selected_columns]
print(filtered_cars)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
import pandas as pd


df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

print(df[['Min.Price', 'Max.Price']].head())
print(df[['Min.Price', 'Max.Price']].isnull().sum())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091
Min.Price    0
Max.Price    0
dtype: int64


⁠4. How to get the rows of a dataframe with row sum > 100?

In [32]:
random_df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rows_greater_than_100 = random_df[random_df.sum(axis=1) > 100]
print(rows_greater_than_100)

     0   1   2   3
0   34  22  17  33
2   36  32  37  34
4   37  27  39  39
7   26  35  20  28
9   38  31  21  26
10  31  10  38  24
12  26  37  13  37
